language: python

python:
  - "3.6"
  - "3.7"

dist: xenial

# setup environment
env:
  global:
    - DJANGO_SETTINGS_MODULE='settings'
    - DB_HOST=localhost
    - DB_PASSWORD=
    - DB_NAME=mp
    - DB_USER=postgres
    - SECRET_KEY=thISkEyisUsedForTravis

# install dependencies
install:
  - pip install -q -r app/requirements.txt
  - pip install codecov
  - docker build -t macports-webapp .
  - >
    docker run -d
    --publish 8080:8080
    --env DB_HOST=$DB_HOST
    --env DB_PASSWORD=$DB_PASSWORD
    --env DB_NAME=$DB_NAME
    --env DB_USER=$DB_USER
    --env SECRET_KEY=$SECRET_KEY
    --name=macports-webapp macports-webapp

# run test scripts
script:
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
  - coverage run --source=. manage.py test
  - coverage report
  - docker ps | grep -q macports-webapp

services:
  - postgresql
  - docker

before_script:
  - psql -c 'create database mp;' -U postgres
  - cd app

addons:
  postgresql: "10"

after_success:
  - codecov
